backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "testing"
    label: "Testing"
    files:
      - name: data
        label: Data
        file: data/data.json
        fields: 
          - name: "list test"
            label: "List test"
            widget: list
            add_to_top: true
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
      # - {label: "Title", name: "title", widget: "string"}
      # - {label: "Description", name: "description", widget: "string"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}